name: CD

'on':
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
          podman login ghcr.io \
          -u ${{ github.actor }} \
          --password-stdin

      - name: Build Image
        run: |
          podman build \
          -t ghcr.io/ashishpatel26/fastapi-app:${{ github.sha }} .

      - name: Push Image
        run: |
          podman push \
          ghcr.io/ashishpatel26/fastapi-app:${{ github.sha }}