name: CI

'on':
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6

      - run: uv sync --frozen

      - run: uv run pytest

      - name: Login Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | \
          podman login docker.io \
          -u ${{ secrets.DOCKERHUB_USERNAME }} \
          --password-stdin

      - run: podman build -t fastapi-app .
